spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      auto-startup: false

logging:
  level:
    com.abhishek.fintech: INFO
    org.springframework.test: INFO
